object Versions {
    const val application = "7.4.1"
    const val androidLibrary = "7.4.1"
    const val android = "1.7.21"
    const val hilt = "2.44"
    const val safeArgs = "2.5.3"
    const val kotlinJvm = "1.8.0"
    const val retrofit = "2.9.0"
    const val bomHttp = "4.10.0"
    const val coroutines = "1.6.4"
    const val inject = "1"
    const val viewBinding = "1.5.8"
    const val glide = "4.14.2"
    const val lifecycle = "2.6.1"
    const val navigation = "2.5.3"
    const val googleServices = "4.3.15"
    const val fireAuth = "21.2.0"
    const val fireAuthKtx = "21.1.0"
    const val playServicesAuth = "20.4.1"
    const val fireBom = "31.2.3"
    const val measurementApi = "21.2.1"
    const val map = "18.1.0"
    const val legasySupport = "1.0.0"
    const val fireProtolite = "18.0.0"
}